### PR TITLE
upgrade addon base to 8.0.1 and separate docs

### PR DESCRIPTION
**Pull request by engrbm87**
Upgrade add-on base to 8.0.1 and separate docs from readme.

### CODE REVIEW

**Comment by pierrickrouxel** [comment]
I read your commit. Where is the doc now ?

**Comment by engrbm87** [comment]
The previous readme.md file is renamed to docs.md
A new readme.md file is created in root.

**Comment by pierrickrouxel** [comment]
Ok. Thank you. I haven’t seen the rename.

**Comment by AlecRust** [comment]
Now no easy way to find the docs when visiting the repo. You have to know to navigate in to the `/transmission` folder.

A clear link to the docs in the main README would be great. Example: https://github.com/hassio-addons/addon-vscode

**Pull request merged**
